name = "inspect-api"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[durable_objects]
bindings = [{ name = "SESSION_DO", class_name = "SessionDO" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]

[[d1_databases]]
binding = "DB"
database_name = "inspect-db"
database_id = "619200f6-cbde-414d-bc6f-44967e6efe73"

[vars]
ENVIRONMENT = "development"

[[services]]
binding = "SANDBOX_SERVICE"
service = "sandbox-manager"
